name: 'Deployment Action'
description: 'Creates a GitHub Deployment'
author: 'DK'

branding:
  icon: 'arrow-up'
  color: 'gray-dark'

inputs:
  environment:
    description: 'Deployment environment'
    required: true
  infrastructure:
    description: 'Deployment infrastructure'
    required: true
  application:
    description: 'Application name'
    required: true
  awsAccount:
    description: 'AWS Account ID'
    required: true
  useLatestManifest:
    description: 'Use the latest manifest configuration'
    required: false
    default: 'true'

runs:
  using: node20
  main: dist/index.js
